CREATE TABLE coaches_career (
  coachid varchar(20),
  firstname varchar(20) NOT NULL,
  lastname varchar(20) NOT NULL,
  season_win int,
  season_loss int,
  playoff_win int,
  playoff_loss int,
  PRIMARY KEY (coachid),
  CHECK (season_win >= 0),
  CHECK (season_loss >= 0),
  CHECK (playoff_win >= 0),
  CHECK (playoff_loss >=0)
);

CREATE TABLE coaches_season (
  coachid varchar(20),
  year int,
  yr_order int,
  firstname varchar(20) NOT NULL,
  lastname varchar(20) NOT NULL,
  season_win int,
  season_loss int,
  playoff_win int,
  playoff_loss int,
  team char(3),
  CHECK (season_win >= 0),
  CHECK (season_loss >= 0),
  CHECK (playoff_win >= 0),
  CHECK (playoff_loss >=0),
  CHECK (year >= 1946),
  CHECK (yr_order >= 1)
);

CREATE TABLE player_playoffs_career (
  ilkid varchar(20),
  firstname varchar(20) NOT NULL,
  lastname varchar(20) NOT NULL,
  leag char(1) NOT NULL,
  gp int,
  minutes int,
  pts int,
  dreb int,
  oreb int,
  reb int,
  asts int,
  stl int,
  blk int,
  turnover int,
  pf int,
  fga int,
  fgm int,
  fta int,
  ftm int,
  tpa int,
  tpm int,

  PRIMARY KEY (ilkid, leag),

  CHECK (gp >= 0),
  CHECK (minutes >= 0),
  CHECK (pts >= 0),
  CHECK (dreb >= 0),
  CHECK (oreb >= 0),
  CHECK (asts >= 0),
  CHECK (reb >= 0),
  CHECK (stl >= 0),
  CHECK (blk >= 0),
  CHECK (turnover >= 0),
  CHECK (pf >= 0),
  CHECK (fga >= 0),
  CHECK (fgm >= 0),
  CHECK (fta >= 0),
  CHECK (ftm >= 0),
  CHECK (tpa >= 0),
  CHECK (tpm >= 0)
);

CREATE TABLE player_playoffs (
  ilkid varchar(20),
  year int,
  firstname varchar(20) NOT NULL,
  lastname varchar(20) NOT NULL,
  team char(3) NOT NULL,
  leag char(1) NOT NULL,
  gp int,
  minutes int,
  pts int,
  dreb int,
  oreb int,
  reb int,
  asts int,
  stl int,
  blk int,
  turnover int,
  pf int,
  fga int,
  fgm int,
  fta int,
  ftm int,
  tpa int,
  tpm int,
  PRIMARY KEY (ilkid, year, team, leag)
  CHECK (gp >= 0),
  CHECK (minutes >= 0),
  CHECK (pts >= 0),
  CHECK (dreb >= 0),
  CHECK (oreb >= 0),
  CHECK (asts >= 0),
  CHECK (reb >= 0),
  CHECK (stl >= 0),
  CHECK (blk >= 0),
  CHECK (turnover >= 0),
  CHECK (pf >= 0),
  CHECK (fga >= 0),
  CHECK (fgm >= 0),
  CHECK (fta >= 0),
  CHECK (ftm >= 0),
  CHECK (tpa >= 0),
  CHECK (tpm >= 0)
);

CREATE TABLE player_regular_season_career (
  ilkid varchar(20),
  firstname varchar(20) NOT NULL,
  lastname varchar(20) NOT NULL,
  leag char(1) NOT NULL,
  gp int,
  minutes int,
  pts int,
  oreb int,
  dreb int,
  reb int,
  asts int,
  stl int,
  blk int,
  turnover int,
  pf int,
  fga int,
  fgm int,
  fta int,
  ftm int,
  tpa int,
  tpm int,
  CHECK (gp >= 0),
  CHECK (minutes >= 0),
  CHECK (pts >= 0),
  CHECK (dreb >= 0),
  CHECK (oreb >= 0),
  CHECK (asts >= 0),
  CHECK (reb >= 0),
  CHECK (stl >= 0),
  CHECK (blk >= 0),
  CHECK (turnover >= 0),
  CHECK (pf >= 0),
  CHECK (fga >= 0),
  CHECK (fgm >= 0),
  CHECK (fta >= 0),
  CHECK (ftm >= 0),
  CHECK (tpa >= 0),
  CHECK (tpm >= 0)
);

CREATE TABLE player_regular_season (
  ilkid varchar(20),
  year int,
  firstname varchar(20),
  lastname varchar(20),
  team char(3),
  leag char(1) NOT NULL,
  gp int,
  minutes int,
  pts int,
  oreb int,
  dreb int,
  reb int,
  asts int,
  stl int,
  blk int,
  turnover int,
  pf int,
  fga int,
  fgm int,
  fta int,
  ftm int,
  tpa int,
  tpm int,
  PRIMARY KEY (ilkid, year, team),
  CHECK (gp >= 0),
  CHECK (minutes >= 0),
  CHECK (pts >= 0),
  CHECK (dreb >= 0),
  CHECK (oreb >= 0),
  CHECK (asts >= 0),
  CHECK (reb >= 0),
  CHECK (stl >= 0),
  CHECK (blk >= 0),
  CHECK (turnover >= 0),
  CHECK (pf >= 0),
  CHECK (fga >= 0),
  CHECK (fgm >= 0),
  CHECK (fta >= 0),
  CHECK (ftm >= 0),
  CHECK (tpa >= 0),
  CHECK (tpm >= 0)
);

CREATE TABLE players (
  ilkid varchar(20),
  firstname varchar(20) NOT NULL,
  lastname varchar(20) NOT NULL,
  position char(1) NOT NULL,
  firstseason int,
  lastseason int,
  h_feet int,
  h_inches int,
  weight int,
  college varchar(20) NOT NULL,
  birthdate datetime,
  PRIMARY KEY (ilkid),
  CHECK (firstseason >= 0),
  CHECK (lastseason >= 0),
  CHECK (h_feet >= 0),
  CHECK (weight >= 0),
  CHECK (birthdate  >= 0)
);

CREATE TABLE teams (
  team CHAR(3) NOT NULL,
 	location VARCHAR(20) NOT NULL,
 	name VARCHAR(20),
 	leag CHAR(1) NOT NULL,
 	PRIMARY KEY (team, leag)
);
